apiVersion: v1
kind: Pod
metadata:
  name: two-container-pod
spec:
  containers:
    - name: app-container
      image: nginx
      ports:
        - containerPort: 80

    - name: sidecar-container
      image: busybox
      command: ["sh", "-c", "while true; do echo hello-from-sidecar; sleep 5; done"]

